# Generated by Django 6.0.1 on 2026-01-15 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('sap_view_dashboard', 'Darf Dashboard sehen'), ('sap_view_equipments', 'Darf Anlagen sehen'), ('sap_view_orders', 'Darf Aufträge lesen'), ('sap_create_order', 'Darf Auftrag/Meldung anlegen'), ('sap_edit_own_orders', 'Darf eigene Aufträge bearbeiten'), ('sap_confirm_order', 'Darf Zeitrückmeldung buchen'), ('sap_edit_all_orders', 'Darf alle Aufträge bearbeiten'), ('sap_release_order', 'Darf Aufträge freigeben'), ('sap_technical_complete', 'Darf technisch abschließen (TECO)')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_plant', models.CharField(blank=True, max_length=4, null=True, verbose_name='SAP Werk')),
                ('sap_personnel_number', models.CharField(blank=True, max_length=20, verbose_name='Personalnr.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
